"""add document chunks

Revision ID: 0002
Revises: 0001
Create Date: 2026-03-26 12:17:40.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('fts_tokens', postgresql.TSVECTOR(), sa.Computed("to_tsvector('italian', content)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], on_delete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Vector Search Index (HNSW with cosine ops)
    op.create_index(
        'idx_chunks_embedding', 
        'document_chunks', 
        ['embedding'], 
        unique=False, 
        postgresql_using='hnsw', 
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'}
    )
    
    # Full Text Search Index (GIN)
    op.create_index(
        'idx_chunks_fts', 
        'document_chunks', 
        ['fts_tokens'], 
        unique=False, 
        postgresql_using='gin'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
